### ISSUE TITLE
Footer: Footer option #2 was not implemented

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#1]
SEO footer option #2
Web Design & Development by <a href=”http://www.titanweb.com.au” <?php if (!is_front_page()) { echo ‘rel=”nofollow”‘; }  ?> target=”_blank” title=”Titan Web”>Titan Web</a><img src=”<?php bloginfo(‘template_url’); ?>/images/titanweb-logo-dark.png” alt=”Titan Web”>

Reference: https://knowledgebase.titanweb.com.au/development/updating-the-footer-for-seo-ranking

**Comment by arielcebudigital** [comment]
SEO footer option #8, check the updated project scope,

**Comment by romatitan** [comment]
The scope was changed to SEO footer option #2 to #8
