### ISSUE TITLE
Enhancement - Order Receipt Notification: Put right margin for "Thank you for your order" receipt title.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#100]
![receipt - 01](https://cloud.githubusercontent.com/assets/12888048/9191235/5568701a-4031-11e5-8a4e-b3dbb04a6b88.jpg)

**Comment by arielcebudigital** [comment]
![order](https://cloud.githubusercontent.com/assets/11186408/9269310/dd71fb46-429a-11e5-9901-7df595396f5f.png)

**Comment by romatitan** [comment]
Enhancement not implemented.
