### ISSUE TITLE
Product Single: To be able to see the product pricing, the user should log-in first

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#102]
Not logged in
![products single - 16](https://cloud.githubusercontent.com/assets/12888048/9191558/391d18ee-4035-11e5-884d-1a9e0bf258d1.jpg)

**Comment by arielcebudigital** [comment]
Only the add to cart button will hide/show if the user is login/logout

**Comment by romatitan** [comment]
Duplicate #57
