### ISSUE TITLE
Gallery: Lightbox Effects wasn't set to "No Lightbox"

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#105]
![gallery - 02](https://cloud.githubusercontent.com/assets/12888048/9191909/0e3e6ab6-4039-11e5-8f2d-90a45adc8307.jpg)

**Comment by arielcebudigital** [comment]
New Template don't have No Lightbox

**Comment by romatitan** [comment]
Lightbox Effects was changed to Custom.
