### ISSUE TITLE
Enhancement: Maintain the notification message in its content area, otherwise, place the "View Cart" button below the message.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#114]
Affected device(s): iPodtouch5, S4
![t5](https://cloud.githubusercontent.com/assets/12888048/9192622/385ad6ee-403f-11e5-8ca0-9f06b2c793bf.jpg)

**Comment by arielcebudigital** [comment]
I don't see any problem on this view, since the text will automatically adjust. :-)

**Comment by romatitan** [comment]
Enhancement not implemented.
