### ISSUE TITLE
Homepage - devices: There's a large white blank space above the testimonial items

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#117]
Affected device(s): iPodtouch5, S4

![homepage - 07](https://cloud.githubusercontent.com/assets/12888048/9192813/dbdf58de-4040-11e5-810b-6c178acd1037.jpg)

**Comment by arielcebudigital** [comment]
I don't see this issue, please refresh

**Comment by romatitan** [comment]
Issue was fixed
