### ISSUE TITLE
Testimonials: Title font-weight was set to 500. It should be 400.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#3]
![testimonials - 01](https://cloud.githubusercontent.com/assets/12888048/9076194/c4794cf2-3b51-11e5-941b-ca1ccb76df34.jpg)

**Comment by arielcebudigital** [comment]
Actually, it's the normal weight for this font, this is generated font from a font - squirrel.,

**Comment by romatitan** [comment]
This is fixed.
Font-weight was changed to normal or 400.
