### ISSUE TITLE
Homepage: page title font-weight was set to 500. It should be 700.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#31]
![homepage - 05](https://cloud.githubusercontent.com/assets/12888048/9078058/d970416c-3b68-11e5-8315-e532e0f1650a.jpg)

**Comment by arielcebudigital** [comment]
Actually, it's the normal weight for this font, this is generated font from a font - squirrel.,

**Comment by romatitan** [comment]
Font weight was fixed to normal.
