### ISSUE TITLE
Contact Us: Phone and Fax contact details were missing.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#41]
![contact - 01](https://cloud.githubusercontent.com/assets/12888048/9103530/b45e724e-3c31-11e5-89dc-f5de637b82f2.jpg)

**Comment by arielcebudigital** [comment]
Please try to add data in those fields.

**Comment by arielcebudigital** [comment]
There are no data for phone and fax in the webcopy but i already test it if you put data on those fields it will display,

**Comment by romatitan** [comment]
Verified fixed.
The page displayed the data for Phone and Fax from the business details
![image](https://cloud.githubusercontent.com/assets/12888048/9321001/3069c5cc-4593-11e5-96b9-921ce52c07c6.png)

Note:
Phone and Fax numbers weren't provided in the web copy.
