### ISSUE TITLE
Product Single: Different drop-down list box styling

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#59]
![products single - 09c](https://cloud.githubusercontent.com/assets/12888048/9158911/59bd240c-3f51-11e5-942c-3359f9c9687f.jpg)
![products single - 09b](https://cloud.githubusercontent.com/assets/12888048/9158912/59bda9b8-3f51-11e5-9a03-7cf9540d7d8e.jpg)
![products single - 09a](https://cloud.githubusercontent.com/assets/12888048/9158910/59bc47ee-3f51-11e5-8313-cf1482caf5b8.jpg)

**Comment by arielcebudigital** [comment]
Please refer to the http://ramax.stage.titanweb.com.au/products/audio-visual/30pfm/
