### ISSUE TITLE
Product Single: Different image size/container.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#63]
![products single - 06](https://cloud.githubusercontent.com/assets/12888048/9158242/a09bc7c2-3f45-11e5-9c63-8eb29b9fee2e.jpg)

**Comment by arielcebudigital** [comment]
What we follow is the grid and it should percentage not pixels.

**Comment by romatitan** [comment]
Verified fixed. It was changed.
