### ISSUE TITLE
Product Single: Inconsistent - Add to cart button wasn't implemented in all products.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#64]
![products single - 07](https://cloud.githubusercontent.com/assets/12888048/9158281/57a9aaba-3f46-11e5-9eea-229046be2ae3.jpg)

**Comment by arielcebudigital** [comment]
Hi Roma, Actually this is not inconsistent, you need to choose first an option for variation product before the add to cart show.
