### ISSUE TITLE
Product Single: The page display 3 variations only. It should display all varaiations of the product.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#69]
![products single - 13](https://cloud.githubusercontent.com/assets/12888048/9158626/d494a48e-3f4c-11e5-8967-5924cfc9ed56.jpg)

**Comment by arielcebudigital** [comment]
You forgot to add price for red, it will only display if there is a price added

**Comment by romatitan** [comment]
All variations has price added.
