### ISSUE TITLE
Cart: Broken table borders.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#73]
Affected browser(s): Opera

![cart - 02](https://cloud.githubusercontent.com/assets/12888048/9158939/cd4cb6c6-3f51-11e5-9f28-95544628baa0.jpg)

**Comment by arielcebudigital** [comment]
It's okay in my end, here is a screenshot
![opera-source-my-parts](https://cloud.githubusercontent.com/assets/11186408/9246366/b4b84d58-41dd-11e5-9045-c6736625c2cc.png)

**Comment by romatitan** [comment]
I have a screenshot above that the cart talbe was broken in Opera browser.
And now it is fixed.
