### ISSUE TITLE
Cart: ( x ) in the remove icon wasn't aligned in the center properly.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#74]
![cart - 03](https://cloud.githubusercontent.com/assets/12888048/9158954/0f660530-3f52-11e5-8c65-bfa66ba59fa9.jpg)

**Comment by arielcebudigital** [comment]
Hi Roma, For this page what we actually focus are the functionality, There is no design PSD for this page...I hope next time you will focus for the functionality of woccommerce.

**Comment by romatitan** [comment]
Even thought there's no design given for a specific page, its implementors responsiblity to make the project working as expected but not only that but it should be well organized and presentable as well.
