### ISSUE TITLE
Cart - Calculate Shipping section: Different drop down arrow style

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#75]
![cart - 04d](https://cloud.githubusercontent.com/assets/12888048/9159085/5f511df8-3f54-11e5-81ea-e140aea71508.jpg)
![cart - 04a](https://cloud.githubusercontent.com/assets/12888048/9159082/5f4ad9ac-3f54-11e5-9a0e-58a5c14b7d9c.jpg)
![cart - 04b](https://cloud.githubusercontent.com/assets/12888048/9159083/5f4e1798-3f54-11e5-8622-c136fc6fb3a6.jpg)
![cart - 04c](https://cloud.githubusercontent.com/assets/12888048/9159084/5f4f05ea-3f54-11e5-8525-09b7dd9180bc.jpg)

**Comment by arielcebudigital** [comment]
Hi, Roma for this page just focus on the functionality, please refer this site http://ramax.stage.titanweb.com.au/products/audio-visual/30pfm/
