### ISSUE TITLE
Enhancement - Checkout: The color for "Place Order" button was #a46497. If possible, change it to #0b3840 and it hover state to #146776 to be consistent with other buttons.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#76]
![cart - 05](https://cloud.githubusercontent.com/assets/12888048/9159179/683c7e92-3f56-11e5-8d89-3ba5c25e5756.jpeg)

**Comment by arielcebudigital** [comment]
Change to Flat style and color

**Comment by romatitan** [comment]
Normal state was changed to 0b3840 and its Hover state to #1a899d
