### ISSUE TITLE
Enhancement: Change the drop-down list box layout/style to flat to be consistent with other fields.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#80]
![checkout - 02](https://cloud.githubusercontent.com/assets/12888048/9159779/cc7870a4-3f61-11e5-97ef-b8fc6bc1c1b6.jpeg)

**Comment by arielcebudigital** [comment]
just check this site:http://ramax.stage.titanweb.com.au/checkout/
we only check the functionality

**Comment by romatitan** [comment]
Enhancement not implemented.
