### ISSUE TITLE
Enhancement - My Account: Change the layout/style of the button ( Save Address ) to flat to be consistent with other buttons

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#83]
Note:
Edit Address ( Save Address button )
- Shipping Address
- Billing Address

![my account - 03](https://cloud.githubusercontent.com/assets/12888048/9160051/5246baca-3f66-11e5-8d35-3fd3e538556f.jpg)
![my account - 02](https://cloud.githubusercontent.com/assets/12888048/9160052/5248fb82-3f66-11e5-80ce-342f3802c066.jpg)

**Comment by arielcebudigital** [comment]
Used Flat Syle
