### ISSUE TITLE
Enhancement: Field's border for set focus. Follow what the Contact form has.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#84]
![my account - 04](https://cloud.githubusercontent.com/assets/12888048/9160069/a15ade16-3f66-11e5-8f61-5729b18edb66.jpg)
![my account - 05](https://cloud.githubusercontent.com/assets/12888048/9160071/ad1d5972-3f66-11e5-8654-59e1fc882f3d.jpg)

**Comment by arielcebudigital** [comment]
Check the http://ramax.stage.titanweb.com.au/checkout/
we only check the functionality

**Comment by romatitan** [comment]
Enhancement not implemented.
