### ISSUE TITLE
General: W3C Error 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#90]
Affected page(s):
Homepage, 
About Us, 
Products, 
News & Events, 
Privacy Policy, 
Thank You
My Account
my-account/edit-address/shipping/
my-account/edit-address/billing/

https://validator.w3.org/nu/?doc=http%3A%2F%2Fsource-my-parts.stage.titanweb.com.au%2F

**Comment by arielcebudigital** [comment]
Plugin generated
