### ISSUE TITLE
Enhancement - Homepage / Pre-Footer: Instead of displaying the purchased history, create a text and instruction that will link to My account page.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Source-My-Parts#99]
e.g
Instruction: "To view your purchased item history, click the link below"
Text to link: "My Account"

Text are not readable.
![prefooter - 01](https://cloud.githubusercontent.com/assets/12888048/9191148/4abe9938-4030-11e5-8a81-897f574c00ec.jpg)

Related issue #98

**Comment by arielcebudigital** [comment]
Already remove

**Comment by romatitan** [comment]
Enhancement not implemented.
